### ISSUE TITLE
Is the x-o10n-sw-preload header required?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [o10n-x/wordpress-pwa-optimization#6]
When enabling service worker push, the plugin adds a header like:

`x-o10n-sw-preload: <https://mydomain.com/assets/style.css>`

Is this header required for the service worker push to work? Or can I safely hide / strip the header (mainly to reduce the size of the header)?

**Comment by optimalisatie** [comment]
Hi Ahmed!

Yes, this is the header used for Service Worker Push. It is similar to the HTTP/2 Push header, `Link: </app/style.css>; rel=preload; as=style;`

Service Worker Push looks a lot like HTTP/2 Server Push from a server side perspective. Both use a HTTP header to expose assets to push. Instead of a web server, the Service Worker in the browser will process the header.
