### ISSUE TITLE
Web App Manifest wont save

### ISSUE THREAD

**Issue by GSby30** [o10n-x/wordpress-pwa-optimization#7]
Cant seem to save the web app manifest after validating it, am I missing something?

**Comment by optimalisatie** [comment]
Thank you very much for reporting the issue!

It was a bug introduced with a recent update to support conditional JSON configuration in version 0.0.35.

https://github.com/o10n-x/wordpress-pwa-optimization/releases/tag/0.0.35

The settings were saved but the JSON was not visible in the editor.

THe bug has been fixed in the latest update.
